### ISSUE TITLE
Required parameter is missing: grant_type

### ISSUE THREAD

**Issue by bhauman** [googleplus/gplus-quickstart-ruby#11]
Hey guys I feel like the Client lib must be out of date?
I'm getting this server error on connect for the default vanilla project.
```
Signet::AuthorizationError - Authorization failed.  Server message:
{
  "error" : "invalid_request",
  "error_description" : "Required parameter is missing: grant_type"
}
```

**Comment by joaomdmoura** [comment]
Same here :+1:

**Comment by gguuss** [comment]
Are you still encountering the issue?  I just tested the sample and it works.
