### ISSUE TITLE
HTTPS error

### ISSUE THREAD

**Issue by MasterSlowPoke** [googleplus/gplus-quickstart-ruby#12]
I'm getting a problem when running this on Chrome

Uncaught SecurityError: Blocked a frame with origin "http://localhost:4567" from accessing a frame with origin "https://accounts.google.com".  The frame requesting access has a protocol of "http", the frame being accessed has a protocol of "https". Protocols must match.

I get this error on Firefox:
Error: Permission denied to access property 'valueOf' , pointing to line 87

Both of them will work after refreshing the page, but that isn't how it's supposed to work. What kind of configuration will allow me to use this with a http domain?

**Comment by gguuss** [comment]
This is how it's supposed to work; for authorization / authentication, you should be using secure communications. For testing with SSL, you could create a self-signed certificate, install it on your client computer's keychain, and then set it up with your local web server. For SimpleHTTPServer, there is this example of how to do this: http://code.activestate.com/recipes/442473-simple-http-server-supporting-ssl-secure-communica/
